name = "Deldir"
uuid = "64db5801-a3ae-51a7-b7d2-a0a5f0813e47"
authors = ["Robert DJ <git@dahl-jacobsen.dk>"]
version = "1.4.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Deldir_jll = "0cb025a2-29c7-561e-a277-a82c5b779c13"

[compat]
DataFrames = "1.3"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
